name: Linting

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: fourmolu/fourmolu-action@v8
      with:
        pattern: |
          sel/**/*.hs
          libsodium-bindings/**/*.hs
  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.5'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
      with:
        path: '["sel", "libsodium-bindings"]'
        fail-on: warning
