name: "libsodium hs nix check"
on:
  pull_request:
  push:
    branches: ["main"]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v13
      with:
        name: libsodium-hs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -Lv --allow-import-from-derivation --fallback
