name: sel

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  native:
    name: ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        ghc: ['8.10', '9.0', '9.2', '9.4']
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v3
      - name: Setup environment
        run: |
          sudo apt install -y libsodium-dev
      - name: Set up Haskell
        id: setup-haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 'latest'
      - name: Freeze
        run: cabal freeze
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
      - name: Build
        run: cabal build sel
      - name: Test
        run: cabal test sel
