name: sel

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["libsodium-bindings"]
    types:
      - completed

jobs:
  generateMatrix:
    name: "Generate matrix from cabal"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: kleidukos/get-tested@0.1.7.1
        with:
          cabal-file: sel/sel.cabal
          ubuntu-version: "latest"
          macos-version: "latest"
          version: 0.1.7.1
  tests:
    name: ${{ matrix.ghc }} on ${{ matrix.os }}
    needs: generateMatrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.generateMatrix.outputs.matrix) }}
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v4
      - name: Set up Haskell
        id: setup-haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 'latest'
      - name: Configure
        run: |
          ./.github/workflows/install-libsodium.sh
      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      - name: Build
        run: cabal build --write-ghc-environment-files=always sel
      - name: Test
        run: cabal test sel
      - name: Diff the expected and actual package APIs
        uses: kleidukos/diff-package-api@v0.1.0.1
        with:
          package-name: sel
          expected-interface: sel/test/package-api-${{ matrix.ghc }}.txt
          ghc: ${{ matrix.ghc }}
          version: 0.1.0.1 # This is the version of the print-api tool
